datasets:
- name: ML-100K
  prefilters: []
  rating_modifier: null
  splitting:
    params: {}
    test_ratio: 0.2
    type: random
- name: ML-100K
  prefilters: []
  rating_modifier: null
  splitting:
    params: {}
    test_ratio: 0.3
    type: random
evaluation: {}
models:
  Elliot:
  - name: FunkSVD
    params:
      batch_size: 512
      epochs: 10
      factors: 10
      lr: 0.001
      reg_b: 0.001
      reg_w: 0.1
      seed: null
  - name: ItemKNN
    params:
      implementation: aiolli
      neighbours: 40
      similarity: cosine
  - name: MultiVAE
    params:
      batch_size: 512
      dropout_keep: 1.0
      epochs: 10
      intermediate_dim: 600
      latent_dim: 200
      lr: 0.001
      reg_lambda: 0.01
      seed: null
  - name: MostPop
    params: {}
  - name: PureSVD
    params:
      factors: 10
      seed: null
  - name: Random
    params:
      random_seed: null
  - name: SVDpp
    params:
      batch_size: 512
      epochs: 10
      factors: 50
      lr: 0.001
      reg_b: 0.001
      reg_w: 0.1
      seed: null
  - name: UserKNN
    params:
      implementation: aiolli
      neighbours: 40
      similarity: cosine
  Implicit:
  - name: AlternatingLeastSquares
    params:
      calculate_training_loss: false
      factors: 100
      iterations: 15
      random_seed: null
      regularization: 0.01
      use_cg: true
      use_native: true
  - name: BayesianPersonalizedRanking
    params:
      factors: 100
      iterations: 100
      learning_rate: 0.01
      random_seed: null
      regularization: 0.01
      verify_negative_samples: true
  - name: LogisticMatrixFactorization
    params:
      factors: 30
      iterations: 30
      learning_rate: 1.0
      neg_prop: 30
      random_seed: null
      regularization: 0.6
  LensKit:
  - name: BiasedMF
    params:
      damping: 5.0
      features: 10
      item_reg: 0.1
      iterations: 20
      method: cd
      random_seed: null
      user_reg: 0.1
  - name: ImplicitMF
    params:
      features: 10
      iterations: 20
      method: cg
      random_seed: null
      reg: 0.1
      use_ratings: false
      weight: 40.0
  - name: PopScore
    params:
      score_method: quantile
  - name: Random
    params:
      random_seed: null
name: 1648941230_HelloFRK
top_K: 10
type: recommendation
