name: Partial lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lintchanges:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Lint changed Python files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            *.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install lenskit
          pip install implicit
          pip install Cython
          pip install scikit-surprise
          pip install pandas
          pip install PyYAML
          pip install rexmex
          
      - name: Lint all changed files
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            pylint $file
          done
