name: pytest-reporter workflow

on:
  workflow_dispatch:
  pull_request:
    branches: stable
  schedule:
    - cron: '0 22 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: lpenz/ghaction-pytest-cov@v1
